# Generated by Django 5.1.4 on 2025-01-14 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('service', models.CharField(max_length=255)),
                ('priority', models.IntegerField(choices=[(7, 'Debug'), (6, 'Info'), (5, 'Notice'), (4, 'Warning'), (3, 'Error'), (2, 'Critical'), (1, 'Alert'), (0, 'Emergency')], default=6)),
                ('message', models.TextField()),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MetricType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('unit', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A friendly name for the node', max_length=100)),
                ('ip_address', models.GenericIPAddressField(help_text='The IP address (or domain) of the agent')),
                ('node_type', models.CharField(choices=[('Control', 'Control'), ('Agent', 'Agent'), ('Database', 'Database')], help_text='Type of node', max_length=50)),
                ('location', models.CharField(choices=[('Europe', 'Europe'), ('US East', 'US East'), ('US West', 'US West')], help_text='Node location', max_length=50)),
                ('ssh_username', models.CharField(help_text='SSH username', max_length=100)),
                ('ssh_password', models.CharField(help_text='SSH password', max_length=100)),
                ('status', models.CharField(default='offline', help_text='online/offline', max_length=10)),
                ('last_check_in', models.DateTimeField(blank=True, help_text='Last time the node responded', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSeriesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value', models.FloatField()),
                ('metric_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.metrictype')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='dashboard.node')),
            ],
        ),
    ]
