# Generated by Django 5.1.4 on 2025-01-17 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.FloatField()),
                ('comparison_type', models.CharField(choices=[('>', 'Greater than'), ('<', 'Less than'), ('>=', 'Greater or equal to'), ('<=', 'Less or equal to'), ('=', 'Equal to'), ('!=', 'Not equal to')], default='>', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='dashboard.metrictype')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='dashboard.node')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
