# Generated by Django 5.1.2 on 2024-11-13 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_logentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='priority',
            field=models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('DEBUG', 'Debug')], max_length=50),
        ),
    ]
