# Generated by Django 5.1.4 on 2025-01-23 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alertrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertrule',
            name='cooldown_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='last_triggered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='severity',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10),
        ),
    ]
