# Generated by Django 5.1.2 on 2024-11-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_logentry_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='hostname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='priority',
            field=models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('NOTICE', 'Notice'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical'), ('ALERT', 'Alert'), ('EMERGENCY', 'Emergency')], max_length=50),
        ),
    ]
