# Generated by Django 5.1.2 on 2024-11-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_logentry_hostname_alter_logentry_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Debug'), (1, 'Info'), (2, 'Notice'), (3, 'Warning'), (4, 'Error'), (5, 'Critical'), (6, 'Alert'), (7, 'Emergency')]),
        ),
    ]
