# Generated by Django 5.1.2 on 2024-11-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_logentry_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='priority',
            field=models.IntegerField(choices=[(7, 'Debug'), (6, 'Info'), (5, 'Notice'), (4, 'Warning'), (3, 'Error'), (2, 'Critical'), (1, 'Alert'), (0, 'Emergency')]),
        ),
    ]
